apiVersion: v1
kind: Pod
metadata:
  name: mongo-init
spec:
  containers:
  - name: mongo-init
    image: mongo:latest
    command:
    - "bash"
    - "-c"
    - |
      sleep 3
      mongosh --host mongodb-0.mongodb:27017 <<EOF
      rs.initiate(
        {
          _id: "rs0",
          members: [
            { _id: 0, host: "mongodb-0.mongodb:27017" },
            { _id: 1, host: "mongodb-1.mongodb:27017" },
            { _id: 2, host: "mongodb-2.mongodb:27017" }
          ]
        }
      )
      EOF
      sleep 10
      mongosh --host mongodb-0.mongodb:27017 <<EOF
      use admin
      db.createUser({
        user: "$MONGO_INITDB_ROOT_USERNAME",
        pwd: "$MONGO_INITDB_ROOT_PASSWORD",
        roles: [{ role: "root", db: "admin" }]
      })
      EOF
    env:
    - name: MONGO_INITDB_ROOT_USERNAME
      valueFrom:
        secretKeyRef:
          name: app-secret
          key: mongo-username
    - name: MONGO_INITDB_ROOT_PASSWORD
      valueFrom:
        secretKeyRef:
          name: app-secret
          key: mongo-password
  restartPolicy: OnFailure
